allowBuilds:
  esbuild: true
  pnpm: true
minimumReleaseAgeExclude:
  - '@typescript/typescript-darwin-arm64@7.1.0-dev.20260925.1'
  - '@typescript/typescript-darwin-x64@7.1.0-dev.20260925.1'
  - '@typescript/typescript-linux-arm64@7.1.0-dev.20260925.1'
  - '@typescript/typescript-linux-arm@7.1.0-dev.20260925.1'
  - '@typescript/typescript-linux-x64@7.1.0-dev.20260925.1'
  - '@typescript/typescript-win32-arm64@7.1.0-dev.20260925.1'
  - '@typescript/typescript-win32-x64@7.1.0-dev.20260925.1'
  - typescript@7.1.0-dev.20260925.1
  - '@astrojs/starlight@0.42.6'
  - astro@7.3.8
